version: "3.9"
services:
  grpc-server:
    build:
      context: .
      dockerfile: dockerfile.grpc
    container_name: grpc_server
    ports:
      - "8585:8585"
    networks:
      - app_network
    env_file:              
      - .env

  envoy:
    build:
      context: .
      dockerfile: dockerfile.envoy
    container_name: envoy
    ports:
      - "10000:10000"
    networks:
      - app_network
    depends_on:
      - grpc-server
    environment:            
      - GRPC_HOST=grpc-server
      - GRPC_PORT=8585
      
networks:
  app_network:
    driver: bridge
